#!/usr/bin/env bash

DIRECTORY="$HOME/.tmux/plugins/tpm"
REPOSITORY_URL="https://github.com/tmux-plugins/tpm"

mkdir --parents $HOME/.tmux/plugins

if [ ! -d "$DIRECTORY" ]; then
  git clone $REPOSITORY_URL $DIRECTORY
else
  pushd "$DIRECTORY"
    git pull $REPOSITORY_URL
  popd
fi

