#!/usr/bin/env bash

NERD_FONTS_ROOT=$HOME/.local/share/fonts/nerd-fonts

if [[ ! -d "$NERD_FONTS_ROOT" ]]; then
  git clone https://codeberg.org/exorcist/fonts.git --depth=1 --branch=master $NERD_FONTS_ROOT
else
  git -C $NERD_FONTS_ROOT pull
fi

fc-cache -fv $NERD_FONTS_ROOT
