#!/bin/bash

set -euxo pipefail

# Following the instructions in https://github.com/alacritty/alacritty/blob/master/INSTALL.md

if [ -x "$(command -v pacman)" ]; then
  sudo pacman -S gzip cmake scdoc freetype2 fontconfig pkg-config make libxcb libxkbcommon python --noconfirm
fi

if [ -x "$(command -v apt)" ]; then
  sudo apt install -y gzip scdoc cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
fi

BUILD_DIR=~/.alacritty.build

if [[ ! -d "$BUILD_DIR" ]]; then
  git clone https://github.com/alacritty/alacritty.git $BUILD_DIR
else
  git -C $BUILD_DIR pull
fi

$HOME/.dependencies/includes/rustup

pushd $BUILD_DIR
  $HOME/.cargo/bin/rustup override set stable
  $HOME/.cargo/bin/rustup update stable
  cargo build --release

  # Terminfo
  sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

  # Desktop entry
  sudo rm --force /usr/local/bin/alacritty
  sudo cp target/release/alacritty /usr/local/bin
  sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
  sudo desktop-file-install extra/linux/Alacritty.desktop
  if [ -x "$(command -v update-desktop-database)" ]; then
    sudo update-desktop-database
  fi

  # Man page
  sudo mkdir -p /usr/local/share/man/man1
  scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
  scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
popd

