#!/bin/bash

set -euxo pipefail

DIRECTORY="$HOME/.config/alacritty/rose-pine"
REPOSITORY_URL="git@github.com:rose-pine/alacritty.git "

if [ ! -d "$DIRECTORY" ]; then
  git clone $REPOSITORY_URL $DIRECTORY
else
  pushd "$DIRECTORY"
    git pull $REPOSITORY_URL
  popd
fi
