#!/bin/bash
set -euxo pipefail

font_dir=~/.local/share/fonts/sf-mono-nerd-font
repo_url=https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git

if [ -d "$font_dir/.git" ]; then
    pushd "$font_dir"
    git pull
    popd
else
    rm -rf "$font_dir"
    git clone "$repo_url" "$font_dir"
fi

fc-cache -f -v
