#! /bin/sh

source $HOME/.xsettings

sxhkd &
nm-applet &
cbatticon &
pasystray &

bspc monitor -d Development Terminal Console Browser Support 06 07 08 Music 10

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
