#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euxo pipefail

export DEPENDENCIES_INCLUDES=~/.dependencies/includes

echo "Running dependencies scripts for your stowed packages."
echo "The scripts can be found in $DEPENDENCIES_INCLUDES"
echo "Distribution-dependent scripts live in in $DEPENDENCIES_INCLUDES/<arch|ubuntu>"

for file in $DEPENDENCIES_INCLUDES/*; do
  if [ -f "$file" ]; then
    "$file"
  fi
done

if grep -Rq "Arch" /etc/*-release; then
  for file in $DEPENDENCIES_INCLUDES/arch/*; do
    "$file"
  done
fi

if grep -REq "Ubuntu|Debian" /etc/*-release; then
  for file in $DEPENDENCIES_INCLUDES/ubuntu/*; do
    "$file"
  done
fi

