#!/usr/bin/env bash

set -euxo pipefail

sudo apt-get install -y wget

NEOVIM_VERSION="v0.9.0"
APPIMG_URL="https://github.com/neovim/neovim/releases/download/$NEOVIM_VERSION/nvim.appimage"
APPIMG_TMP="$(mktemp)"

wget -O "$APPIMG_TMP" "$APPIMG_URL"
chmod +x "$APPIMG_TMP"
sudo mv "$APPIMG_TMP" /usr/bin/nvim

sudo apt-get install -y python3-neovim golang

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
