#!/usr/bin/env bash

set -euxo pipefail

sudo apt-get install -y wget

NEOVIM_VERSION="v0.8.1"

DEB_URL="https://github.com/neovim/neovim/releases/download/$NEOVIM_VERSION/nvim-linux64.deb"
TEMP_DEB="$(mktemp)"
wget -O "$TEMP_DEB" "$DEB_URL"
sudo dpkg -i "$TEMP_DEB"
rm -f "$TEMP_DEB"

sudo apt-get install -y python3-neovim golang

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
