return {
  "AndrewRadev/tagalong.vim",
  "antoinemadec/FixCursorHold.nvim",
  "christoomey/vim-tmux-navigator",
  "farmergreg/vim-lastplace",
  "folke/which-key.nvim",
  "jxnblk/vim-mdx-js",
  "kevinhwang91/nvim-bqf",
  "kristijanhusak/vim-dadbod-ui",
  "lewis6991/gitsigns.nvim",
  "machakann/vim-swap",
  "matze/vim-move",
  "mbbill/undotree",
  "nvim-lua/plenary.nvim",
  "nvim-tree/nvim-web-devicons",
  "tpope/vim-abolish",
  "tpope/vim-commentary",
  "tpope/vim-dadbod",
  "tpope/vim-eunuch",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-surround",
  "tversteeg/registers.nvim",
  { "Mofiqul/vscode.nvim", priority = 51 },
  { "b0o/mapx.nvim",       priority = 51, opts = { whichkey = true } },
}
