return {
  "AndrewRadev/tagalong.vim",
  "antoinemadec/FixCursorHold.nvim",
  "christoomey/vim-tmux-navigator",
  "folke/which-key.nvim",
  "machakann/vim-swap",
  "matze/vim-move",
  "nvim-tree/nvim-web-devicons",
  "tpope/vim-abolish",
  "tpope/vim-commentary",
  "tpope/vim-dadbod",
  "tpope/vim-eunuch",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-surround",
  { "b0o/mapx.nvim",            priority = 51, opts = { whichkey = true } },
  { "kevinhwang91/nvim-bqf",        lazy = true },
  { "kristijanhusak/vim-dadbod-ui", lazy = true },
  { "lewis6991/gitsigns.nvim",      config = true },
  { "mbbill/undotree",          lazy = true },
  { "nvim-lua/plenary.nvim",    priority = 51 },
  { "tversteeg/registers.nvim", lazy = true },
}
