#!/usr/bin/env bash

sudo pacman -S ttf-cascadia-code network-manager-applet geoclue pasystray unclutter xcompmgr hsetroot xorg-xset xorg-setxkbmap arandr autorandr gnome-keyring libsecret seahorse slock dunst brightnessctl qt5ct cbatticon --noconfirm

trizen --noedit -S dmenu-rs j4-dmenu-desktop
